<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Could not connect to {addres}:{port} - {error}' => '',
  'Could not connect to {server} {port} - {error}' => '',
  'Could not set SO_REUSEADDR: {error}' => '',
  'GSocket failed to open the connection: {error}' => '',
  'GSocket.remote_address or GSocket.remote_port cannot be empty' => '',
);
